name: Windsurf Alert

on:

  workflow_dispatch:

  schedule:

    - cron: "0 6 * * *"

jobs:

  windsurf-alert:

    runs-on: ubuntu-latest

    steps:

      - name: Recuperer le programme

        uses: actions/checkout@v4

      - name: Installer Python

        uses: actions/setup-python@v5

        with:

          python-version: "3.12"

      - name: Verifier la meteo

        env:

          NTFY_SERVER: https://ntfy.sh

          NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}

        run: python run_once.pyu
